version: '3.7'

services:

  pyp2ui:
    container_name: pyp2-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:80'
    environment: 
      REACT_APP_API_URL: '${REACT_APP_API_URL}'  